// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/payments/authorize": {
            "post": {
                "description": "Authorize a payment.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "Authorize a payment.",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "payment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_KauanCarvalho_fiap-sa-payment-service_internal_core_usecase_dto.AuthorizePaymentInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_KauanCarvalho_fiap-sa-payment-service_internal_application_dto.PaymentOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_KauanCarvalho_fiap-sa-payment-service_internal_application_dto.APIErrorsOutput"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_KauanCarvalho_fiap-sa-payment-service_internal_application_dto.APIErrorsOutput"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_KauanCarvalho_fiap-sa-payment-service_internal_application_dto.APIErrorsOutput"
                        }
                    }
                }
            }
        },
        "/healthcheck": {
            "get": {
                "description": "Checks the health of the application (connection to database)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "HealthCheck"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_KauanCarvalho_fiap-sa-payment-service_internal_application_dto.HealthCheckOutput"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_KauanCarvalho_fiap-sa-payment-service_internal_application_dto.APIErrorsOutput"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_KauanCarvalho_fiap-sa-payment-service_internal_application_dto.APIErrorOutput": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "string"
                },
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_KauanCarvalho_fiap-sa-payment-service_internal_application_dto.APIErrorsOutput": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_KauanCarvalho_fiap-sa-payment-service_internal_application_dto.APIErrorOutput"
                    }
                }
            }
        },
        "github_com_KauanCarvalho_fiap-sa-payment-service_internal_application_dto.HealthCheckOutput": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_KauanCarvalho_fiap-sa-payment-service_internal_application_dto.PaymentOutput": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "external_reference": {
                    "type": "string"
                },
                "payment_method": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "qr_code": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_KauanCarvalho_fiap-sa-payment-service_internal_core_usecase_dto.AuthorizePaymentInput": {
            "type": "object",
            "required": [
                "amount",
                "external_reference",
                "payment_method"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "external_reference": {
                    "type": "string"
                },
                "payment_method": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "fa-sa-payment-service",
	BasePath:         "",
	Schemes:          []string{"http"},
	Title:            "Fiap SA Payment Service",
	Description:      "Rest API for Fiap SA Payment Service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
