apiVersion: v1
kind: Service
metadata:
  name: payment-service-api
spec:
  type: ClusterIP
  selector:
    app: payment-service-api
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service-api
spec:
  type: LoadBalancer
  selector:
    app: payment-service-api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
