name: Deploy to EKS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}

jobs:
  deploy:
    name: Build & Push image to ECR & Deploy to EKS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate image tag (app + timestamp + commit)
        id: metadata
        run: |
          APP_NAME="fiap_sa_payment_service"
          TIMESTAMP="$(date +'%Y%m%d-%H%M%S')"
          COMMIT="${GITHUB_SHA::7}"
          echo "TAG=${APP_NAME}-${TIMESTAMP}-${COMMIT}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        id: build-and-push
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.TAG }}"
          docker build --target release -t $IMAGE_URI .
          docker push $IMAGE_URI
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.CLUSTER_NAME }}

      - name: Replace envs in Kubernetes manifests
        env:
          IMAGE_URI: ${{ env.IMAGE_URI }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
        run: |
          export AWS_ACCESS_KEY_ID_B64=$(echo -n "$AWS_ACCESS_KEY_ID" | base64 | tr -d '\n')
          export AWS_SECRET_ACCESS_KEY_B64=$(echo -n "$AWS_SECRET_ACCESS_KEY" | base64 | tr -d '\n')
          export AWS_SESSION_TOKEN_B64=$(echo -n "$AWS_SESSION_TOKEN" | base64 | tr -d '\n')
          export DATABASE_URI_B64=$(echo -n "$DATABASE_URI" | base64 | tr -d '\n')
          envsubst < k8s/secrets.tmpl.yml > k8s/secrets.yml
          envsubst < k8s/deployments.tmpl.yml > k8s/deployments.yml

      - name: Validate Kubernetes manifests
        run: |
          kubectl apply --dry-run=client -f k8s/config-map.yml
          kubectl apply --dry-run=client -f k8s/secrets.yml
          kubectl apply --dry-run=client -f k8s/deployments.yml
          kubectl apply --dry-run=client -f k8s/services.yml
          kubectl apply --dry-run=client -f k8s/hpa-api.yml

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/config-map.yml
          kubectl apply -f k8s/secrets.yml
          kubectl apply -f k8s/deployments.yml
          kubectl apply -f k8s/services.yml
          kubectl apply -f k8s/hpa-api.yml

      - name: Wait for deployment rollout
        run: |
          kubectl rollout status deployment/payment-service-api --timeout=140s
          kubectl rollout status deployment/payment-service-worker --timeout=140s

      - name: Debug rollout failure (if needed)
        if: failure()
        run: |
          echo "=== Recent events ==="
          kubectl get events --sort-by='.lastTimestamp' | tail -n 20 || true
